### PR TITLE
Lab 2

### PR DESCRIPTION
**Pull request by ngkavin**
Add initial effort for lab 2

### CODE REVIEW

**Comment by ngkavin** [comment]
@Chkoda @yinqiu88

**Comment by Chkoda** [comment]
Problem 1A, line [6] The distribution seems to have moved away from the original mean, contrary to the statement after it that says it gets closer to the mean (For summing, not averaging). The spread of the distribution does get smaller and approaches a Gaussian shape though. Might want to explain what you are doing in text in problem 1A.

**Comment by Chkoda** [comment]
Problem 1C, at the end when calculating sigma significance you use the pmf function when you should be using the sf function (or 1-cdf function) to calculate the probability of getting "seen" number of rays *or more* from the background. Using just the pmf gives you the probability of getting that many rays, period. The difference is negligible because the "seen" number is so large it still gives almost 33sigma (the sf function is ~~ pmf at such a large value) but for other values it might be important.

`N = 25
seen = Y*N
seen_prob = stats.poisson.sf(seen, X)
stats.norm.isf(seen_prob)`

**Comment by Chkoda** [comment]
For Problem 2, The plots y axis is not right because you are using the discrete formula which has no dx term for convolution; during the convolution of two continuous distributions, you need to multiply the final probabilities by the step size (<1).

'chi2_dist = np.linspace(0, 20, 1000)'
dx = chi2_dist[1] - chi2_dist[0]
'chi2_prob = stats.chi2.pdf(chi2_dist, 3) ***dx** '
'plt.plot(chi2_dist, chi2_prob)'

**Comment by Chkoda** [comment]
Problem 4C, I think you misspoke when saying the chance of a signal-like background event is substantially lower over many trials. Or maybe I'm just confused. Anyway I think the reason it only needs to be slightly brighter is because of the rapidly decreasing probability of brighter events occurring.

**Comment by Chkoda** [comment]
For the extra credit, you state that a 5 sigma event would occur at a value of 20 because the standard deviation times 5 equals 20; I don't think this is right, and you can check it with this 
`chi2_prob = stats.chi2.sf(20, df=8)`
`stats.norm.isf(chi2_prob)`
which outputs a significance of 2.31 sigma. 

Then for the next line you use the command chi2.isf to calculate significance when significance is calculated using the norm.isf or ppf function (look at slides from like first or second day). And that line of code also has a signal strength already inputted, and you're outputting a signal strength for 5 sigma event thats different from the one inputted; the code should look like

`fivesigmaprobability = stats.norm.sf(5)`
`chi2_signal_100 = stats.chi2.isf(fivesigmaprobability, df=8)`

Where chi2_signal_100 is your signal strength for 5 sigma probability. Looks like this error continues throughout.

**Pull request merged**
