### PR TITLE
Lab 3

### PR DESCRIPTION
**Pull request by ngkavin**
Initial draft of lab 3 open for comments

### CODE REVIEW

**Comment by ngkavin** [comment]
@Chkoda @yinqiu88

**Comment by Chkoda** [comment]
Problem 1, 
5 = integral from infinity to x of pdf(x)dx doesn't make sense since the integral from 0 to infinity of a pdf is always one. Sigma is calculated using the quantile function (look on wikipedia) if you really want to get into it, but I think its acceptable to just write .ppf(Probability). 

`fivesigma = 1 - stats.norm.cdf(5)`, which you can write out in the form of an integral, and then finding the value that gives a 5 sigma confidence would be done the following way: 
`value = 1 - stats.norm.ppf(1 - 5 sigma, scale = 0.4, loc = 12)` which you did properly, but I just think you should write it out where it asks you to state the question in math.

**Comment by Chkoda** [comment]
At the end of Problem 1,
I think the 68-95-99.7 rule mostly applies because we're looking at a Gaussian distribution to which that rule applies anyway. So, maybe the only thing we can predict is that increasing the threshold increases errors of commission, and vice versa, but if it were a different distribution then the rule would not apply. You might have some better way to calculate the expected amount of false positives and true negatives though, if you cared.

**Comment by Chkoda** [comment]
Problem 2 part 2, 
Same problem with the integral for finding 5 sigma here. Should it be 5sigma = *-1* x integral from infinity to x of the pdf?

**Comment by Chkoda** [comment]
Problem 3,
Which is more likely, getting heads 4 out of 5 times or 400 out of 500 times? Just trying to demonstrate that its a different question with different significance values. 
When you calculate using the code,
`sigma = stats.norm.ppf(stats.poisson.cdf(6800, 7200))`
you get a sigma of 4.75 as opposed to 0.245. So basically I think you're making a mistake in only looking at 30 minutes as opposed to the whole 15 days, since its a persistent signal and gets more unusual with time, but I don't know for sure what the right answer is. Also, I don't think that's what a negative sigma value means necessarily. Look back at Lab 1 or whenever we had to talk about what a negative sigma value means, because if you set the problem up right it should usually be a positive number (think drawing free body diagrams, if you do it wrong you just get a negative answer). I think the magnitude is all that matters though so long as you get that right.

**Pull request merged**
