### PR TITLE
Lab 4

### PR DESCRIPTION
**Pull request by ngkavin**

### CODE REVIEW

**Comment by ngkavin** [comment]
@sfzhu

**Comment by Chkoda** [comment]
@ngkavin For problem 2,  I think you don't properly test for transient events; you should be doing the difference between images, and looking for things that have really high intensity, like the other lab where we were looking at the difference of two images to find asteroids. Since super novas can be far away and dim by the time they're observed, testing for maximum values doesn't really help you distinguish what it is. The only thing that helps you determine what is a supernova vs what is a nearby and bright star is whether it is there in the next picture or not.

**Comment by Chkoda** [comment]
For problem 1, you don't compare the model you created to the actual data but when talking about it you call it not the best model as its very spiky, etc. but I think it's a pretty good model! If you look at [https://en.wikipedia.org/wiki/South_Atlantic_Anomaly](The South Atlantic Anomaly) it really is just a spike in radiation as you orbit the Earth, because it's a special spot in the magnetic field. I think you should try comparing it to the data, not just say its spiky and therefore not very good.  Those are averages of spiky data, anyway.

**Comment by sfzhu** [comment]
Hi, you could use the difference to find the transient, the difference of two normal distribution is still a normal distribution and the background will just cancel out.

**Pull request merged**
